### ISSUE TITLE
Everytime I change window this pops up

### ISSUE THREAD

**Issue by RakibRyan** [Fifut/godot-time-tracker#3]
![Screenshot 2024-05-06 215242](https://github.com/Fifut/godot-time-tracker/assets/85598032/f0a5f5dd-07eb-4c72-b877-9b1e02065ac6)

If this was intentional please remove it/add a button to keep tracking until i close. changing the window for 2 seconds for importing assets or to lookup something doesn't mean it's not work. maybe add a section which just tracks unfocused time/ named as research. and maybe add a timer that if godot is not focused for more than 10 minutes only then it stops counting time. The same problem happens when I'm running the game too.

**Comment by Fifut** [comment]
Hello.
Unfortunatly, I can't reproduce this issue.
Can you send me a simple project that shows it?

In fact, after 5 min of unfocus the timer stops. 
If I have time, I'll add an option to customize this time.
A section for the unfocus time is a good idea.
I'll add too.

Fell free to send PR

**Comment by RakibRyan** [comment]
in the current version it doesn't happen. I don't know what changed. but it works fine now.
